### ISSUE TITLE
Related Posts Block

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-gutenberg#10]
Duplicate our current Related Post Block functionality as a Gutenblock.

http://gutenberg.wdslab.com/acf-blocks-page/

**Requirements**

- [x] Background Image, Video, and Color
- [x] Title
- [ ] Manual Post Selector (up to 3)
- [x] Font Color
- [x] Custom CSS Class

**Screenshot**

![screenshot](https://dl.dropbox.com/s/whp3a6dv352toba/Screenshot%202018-02-15%2014.54.45.png?dl=0)

**Comment by jomurgel** [comment]
The search component referenced above has been rolled into this block.

## Added
- Search queries the API and puts results into the "Posts" left container.
- Posts are requested on scroll page by page until reach end. If all posts are fetched we stop the ability to receive or fetch saving us from a 400 response.
- Pen was updated to show new component structure as well, Pen: https://codepen.io/jomurgel/pen/MVjdgW?editors=0010

## ToDo
Still, a bit to do here along with the few items above not finished.
- [ ] Add selected posts from search query to attributes. Currently, this does not append to our props and won't render to the front end.
- [ ] Address issues with posts selection that appear in the `allPosts` state AND the `queriedPosts` showing up in multiple places, and/or being allowed to be selected twice.
- [ ] If queried post is selected, it should no longer appear in the `allPosts` array.

Feels like a step back here, but I think this is a move in the right direction.

## Search comonent usage
Import 
``` javascript
import Search from '../../components/search';
```

Call
``` javascript
<Search onQueryChange={ this.returnQueryData } />
```

`onQueryChange` is a callback function that will set our state with data passed up from our `Search` component.

``` javascript
// responseQuery = array of posts
returnQueryData( responseQuery ) {
    this.setState( { queriedPosts: responseQuery } );
}
```

The search component itself is making a simple api request from `this.apiQueryURL = ( query ) => wpApiSettings.root + `wp/v2/posts?search=${ query }&filter[posts_per_page]=-1`;` which makes a simple search query. The results of which are passed up and recieved using that function above.

**Comment by jomurgel** [comment]
I may have worked out a potential fix for the issue above, but need a little more digging. Might also think about seeing if there is a better way to handle data from our posts query, our search query, and selected. 👍

**Comment by jomurgel** [comment]
Built out the search and related posts components to handle data a little more gracefully. Tackled a few tasks from above.

I rewrote the search handling and post output handling to add data rather than removing data from one array to another array.

This may basically complete #28. Essentially our `<Output>` component will, if an item has been selected (onClick Handler) pass the post object to a `selectedPosts` array in our state.

I also added some checks to disable clicking and adjust styles on click if our post was moved from our main posts query to our `selectedPosts` array.

This check also handles the search results query.

- [ x ] Rework data structure
- [ x ] Pass query string up to parent from search component? May add a valid data point to compare against.
- [ x ] Add selected posts from search query to attributes. Currently, this does not append to our props and won't render to the front end.
- [ x ] Address issues with posts selection that appear in the allPosts state AND the queriedPosts showing up in multiple places, and/or being allowed to be selected twice.
- [ x ] If queried post is selected, it should no longer appear in the allPosts array.

![kapture 2018-03-25 at 15 38 36](https://user-images.githubusercontent.com/5230729/37880275-dbd3662e-3042-11e8-98b1-f6f3b1d21a6d.gif)

## New Pending on this task
- [ ] Support for Custom Post Types + Taxonomies
- [ ] Support max post count +metabox notice if trying to add more.
- [ ] Add meta box notice if post trying to save 0 selected posts.
- [ ] Add default background/styling from global WDS components.
- [ ] Output built markup instead of just a list of linked titles.
- [ ] Bind keyboard to item onKeyDown={this.handleKeyDown}.

Might roll some of these ^^ into a search component update.

**Comment by jomurgel** [comment]
Made some updates this weekend to fix some problems that arose as a result of the recent Gutenberg update.

**Comment by coreymcollins** [comment]
Been working on this a little bit to try and get the frontend and backend visual markup in place.  I have it somewhat working, but it breaks once you refresh the page:
![](https://dl.dropbox.com/s/53327jj4kalzwrn/gutenberg-related-posts-switching-we-did-it.gif?dl=0)

Since it's non-working at the moment, I want to wait before committing anything to the repo - but this is a work in progress at the moment.

**Comment by jomurgel** [comment]
Made several updates here to ensure that our posts content and saved state are identical when reloading the page. Essentially we converted our post objects to JSON to save as a string in our post content attributes object for recall on reload.

We added a new attribute — string — for holding the JSON and utilize that on load to render our block. On save the attribute and post content should be identical.

This also might be a workaround or a solution for #32 or accessing anything other than a string in the php `render_callback` function. 

Will be rolling in work Corey did (above) with the new code added today.
